### ISSUE TITLE
SET-UP ???

### ISSUE THREAD

**Issue by ismetsener** [dachcom-digital/pimcore-social-data#8]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? |no
| BC Break report? | no
| RFC?             | no

I installed this plugin,
bu what to at step SETUP

*****************************
The Data Class needs to provide some predefined fields and needs to implement the SocialPostInterface. Just import the preconfigured SocialPost Definition to kickstart your data class.
*********************************

**Comment by solverat** [comment]
The [available Documentation](https://github.com/dachcom-digital/pimcore-social-data/blob/master/docs/00_Setup.md) should be enough.

Create a new DataObject called `SocialPost` and import the definition from https://github.com/dachcom-digital/pimcore-social-data/blob/master/src/SocialDataBundle/Resources/install/class/SocialPost.class.json

**Comment by ismetsener** [comment]
Hi,
where I have to insert this comment 
            $collection->addBundle(new SocialData\Connector\Facebook\SocialDataFacebookConnectorBundle());

in "/opt/pimcore/src/Kernel.php":


```
    public function registerBundlesToCollection(BundleCollection $collection)
    {
        if (class_exists('\\AppBundle\\AppBundle')) {
            $collection->addBundle(new \AppBundle\AppBundle);

        }

        if (class_exists('\Pimcore\Bundle\LegacyBundle\PimcoreLegacyBundle')) {
            $collection->addBundle(new \Pimcore\Bundle\LegacyBundle\PimcoreLegacyBundle);

        }

    }
```

**Comment by solverat** [comment]
Yes, in Kernel.php. Please use the community channels for supporting questions.
