### ISSUE TITLE
Optional configuration

### ISSUE THREAD

**Issue by jansarmir** [dachcom-digital/pimcore-social-data#9]
https://github.com/dachcom-digital/pimcore-social-data/blob/571856b1da17229e80d360df8b14a3c691536ee6/src/SocialDataBundle/Dto/BuildConfig.php#L34

Connectors that dont needsEngineConfiguration fail in process, because they dont have configuration
$engineConfiguration should be nullable

**Comment by solverat** [comment]
True. Every connector needs to provide a configuration class. You could just create a dummy engine configuration.
